<?php
/**
 * Title: Table
 * Slug: table
 * Categories: Grid
 * Keywords: columns, table, school, smarty education, education
 * Inserter: yes
 */
 ?>
<!-- wp:table {"style":{"typography":{"fontSize":"16px","fontStyle":"normal","fontWeight":"400"},"border":{"width":"1px","style":"dotted"}},"borderColor":"foreground","textColor":"foreground","className":"is-style-stripes"} -->
<figure class="wp-block-table is-style-stripes" style="font-size:16px;font-style:normal;font-weight:400"><table class="has-foreground-color has-text-color has-foreground-border-color has-border-color" style="border-style:dotted;border-width:1px"><thead><tr><th class="has-text-align-left" data-align="left">Title</th><th class="has-text-align-left" data-align="left">Name</th><th class="has-text-align-left" data-align="left">Qualifications</th></tr></thead><tbody><tr><td class="has-text-align-left" data-align="left">Principal</td><td class="has-text-align-left" data-align="left">Mrs J.McQuaid</td><td class="has-text-align-left" data-align="left">BSc(Hons)</td></tr><tr><td class="has-text-align-left" data-align="left">Vice Principal</td><td class="has-text-align-left" data-align="left">Mrs S.Monk</td><td class="has-text-align-left" data-align="left">BEd</td></tr><tr><td class="has-text-align-left" data-align="left">Vice Principal</td><td class="has-text-align-left" data-align="left">Mr S.McGuinness</td><td class="has-text-align-left" data-align="left">BSc(Hons)</td></tr><tr><td class="has-text-align-left" data-align="left">Chief Operating Officer</td><td class="has-text-align-left" data-align="left">Mr S.Beeson</td><td class="has-text-align-left" data-align="left">BA(Hons)</td></tr><tr><td class="has-text-align-left" data-align="left">Assistant Vice Principal</td><td class="has-text-align-left" data-align="left">Mr D.Bannister</td><td class="has-text-align-left" data-align="left">BA(Hons)</td></tr><tr><td class="has-text-align-left" data-align="left">Head of Sixth Form</td><td class="has-text-align-left" data-align="left">Miss J.Armstrong</td><td class="has-text-align-left" data-align="left">BSc(Hons)</td></tr><tr><td class="has-text-align-left" data-align="left">Assistant Vice Principal</td><td class="has-text-align-left" data-align="left">Mr N.Giles</td><td class="has-text-align-left" data-align="left">BEc,MA</td></tr></tbody></table></figure>
<!-- /wp:table -->